#!/usr/bin/env ruby
# CriticMarkup accept change script for BBEdit

myMark = STDIN.read

# CriticMarks
# -----------
# Addition {++ ++}
# Deletion {-- --}
# Substitution {~~ ~> ~~}
# Comment {>> <<}
# Highlight {== ==}{>> <<}

addition_mark = /^\{\+\+(.+?)\+\+\}$/
deletion_mark = /^\{\-\-(.+?)\-\-\}$/
sub_mark = /^\{\~\~(.+?)\~\>(.+?)\~\~\}$/
comment_mark = /^\{\>\>(.+?)\<\<\}/
highlight_mark = /^\{\=\=(.+?)\=\=\}\{\>\>(.+?)\<\<\}$/

if addition_mark =~ myMark
  print myMark.gsub(addition_mark, "\\1").chomp
  elsif  deletion_mark =~ myMark
    print ""
  elsif sub_mark =~ myMark
    print myMark.gsub(sub_mark, "\\2").chomp
  else 
end